from .columns import _normalize_header_map, _resolve_column, detect_columns
from .generation_metadata import inject_generation_metadata
from .output_paths import (
    build_country_token,
    ensure_country_placeholder,
    resolve_country_output_path,
    resolve_single_country_output_path,
    trim_logo_anim_flag_for_country,
)
from .sectioned_mode import convert_sectioned_mode
from .simple_mode import convert_simple_mode
from .table_reader import _read_table, _sniff_delimiter
from .timecode import parse_timecode, safe_int
from .unified_processors import (
    UnifiedState,
    build_country_orientation_data,
    build_country_payload,
    build_unified_multi_country_output,
    collect_country_texts,
    deduplicate_rows_by_line_timing,
    join_claim_rows_by_timing,
    join_claim_rows_by_timing_per_video,
    merge_and_dedup_video_rows,
    merge_disclaimer_blocks,
    merge_disclaimer_rows_by_video,
    merge_rows_with_same_line,
    normalize_controller_record,
    normalize_duration_token,
    process_claim_row,
    process_controller_row,
    process_disclaimer_row,
    process_endframe_row,
    process_meta_global_row,
    process_meta_local_row,
    populate_video_level_fields,
    process_logo_row,
    process_sub_row,
    process_super_a_row,
    process_super_b_row,
    propagate_all_scope_texts,
)
from .validation_reports import write_validation_report

__all__ = [
    "parse_timecode",
    "safe_int",
    "_normalize_header_map",
    "_resolve_column",
    "detect_columns",
    "inject_generation_metadata",
    "ensure_country_placeholder",
    "build_country_token",
    "resolve_country_output_path",
    "resolve_single_country_output_path",
    "trim_logo_anim_flag_for_country",
    "convert_simple_mode",
    "convert_sectioned_mode",
    "_sniff_delimiter",
    "_read_table",
    "write_validation_report",
    "UnifiedState",
    "build_country_orientation_data",
    "build_country_payload",
    "build_unified_multi_country_output",
    "normalize_controller_record",
    "normalize_duration_token",
    "collect_country_texts",
    "join_claim_rows_by_timing",
    "join_claim_rows_by_timing_per_video",
    "merge_disclaimer_blocks",
    "merge_disclaimer_rows_by_video",
    "merge_rows_with_same_line",
    "deduplicate_rows_by_line_timing",
    "merge_and_dedup_video_rows",
    "propagate_all_scope_texts",
    "process_meta_global_row",
    "process_meta_local_row",
    "populate_video_level_fields",
    "process_claim_row",
    "process_disclaimer_row",
    "process_logo_row",
    "process_endframe_row",
    "process_sub_row",
    "process_super_a_row",
    "process_super_b_row",
    "process_controller_row",
]
