// Expressions Library — expressions_library.jsx
// Registry of named AE expression strings used by layer_template.jsx.
// Keys are symbolic names referenced from layer_templates_library.jsx item definitions.
// Expression strings are raw AE expression source — do not include JSON escaping.
//
// Usage: always loaded by layer_template.jsx via $.evalFile before item execution.
// Direct execution produces no side effects.

#target aftereffects

(function initExpressionsLibrary(globalObj) {
    if (!globalObj) return;
    if (!globalObj.AE_EXPRESSIONS || typeof globalObj.AE_EXPRESSIONS !== "object") {
        globalObj.AE_EXPRESSIONS = {};
    }

    // ── info ─────────────────────────────────────────────────────────────────

    // info_source_text
    // Builds an informational multiline debug string from the linked data.json footage.
    // Combines global metadata and resolved video-level metadata for QA inspection.
    // Reads FOOTAGE_NAME from the project. Orientation-aware via comp AR.
    globalObj.AE_EXPRESSIONS["info_source_text"] = [
        '// sourceText_json_info — per-video metadata inspector',
        'var FOOTAGE_NAME = "data.json";',
        'var nameShift = 1;',
        'var ar = thisComp.width / Math.max(1, thisComp.height);',
        'function orientFromAR(r){ return r > 1 ? "landscape" : "portrait"; }',
        'var compOrientTest = orientFromAR(ar);',
        'var nameLower = thisComp.name.toLowerCase();',
        'if (nameLower.indexOf("_landscape") >= 0) compOrientTest = "landscape";',
        'else if (nameLower.indexOf("_portrait") >= 0) compOrientTest = "portrait";',
        'var token1 = 0 + nameShift;',
        'var token2 = 1 + nameShift;',
        'function baseVideoId() {',
        '  var p = thisComp.name.split("_");',
        '  return (p.length >= 2) ? (p[token1] + "_" + p[token2]) : "";',
        '}',
        'var baseId = baseVideoId();',
        'var orientedId = baseId ? (baseId + "_" + compOrientTest) : "";',
        'var directId = thisComp.name;',
        'function findVideo(data, candidates) {',
        '  if (!data || !data.videos) return null;',
        '  var vids = data.videos;',
        '  for (var c = 0; c < candidates.length; c++) {',
        '    var target = (candidates[c] + "").toLowerCase();',
        '    if (!target) continue;',
        '    for (var i = 0; i < vids.length; i++) {',
        '      if ((vids[i].videoId + "").toLowerCase() === target) return vids[i];',
        '    }',
        '  }',
        '  return null;',
        '}',
        'function safe(obj, path, defVal) {',
        '  try {',
        '    var ref = obj;',
        '    for (var i = 0; i < path.length; i++) { if (!ref) return defVal; ref = ref[path[i]]; }',
        '    return (ref == null) ? defVal : ref;',
        '  } catch(e) { return defVal; }',
        '}',
        'function toStr(v){ return (v == null) ? "-" : (v + ""); }',
        'var sizeX = thisComp.width; var sizeY = thisComp.height;',
        'function gcd(x,y){ return (y===0)?x:gcd(y,x%y); }',
        'var r = gcd(sizeX,sizeY); var resultAspect = (sizeX/r)+":"+(sizeY/r);',
        'var out = "";',
        'try {',
        '  var data = footage(FOOTAGE_NAME).sourceData;',
        '  var globalMeta = data ? data.metadataGlobal : null;',
        '  var video = findVideo(data, [orientedId, directId, baseId]);',
        '  out += "aspect: " + resultAspect + "\\n";',
        '  out += "orient: " + compOrientTest + "\\n";',
        '  out += "client: " + toStr(safe(globalMeta,["client"],"-")) + "\\n";',
        '  out += "campaign: " + toStr(safe(globalMeta,["campaign"],"-")) + "\\n";',
        '  if (video) {',
        '    out += "videoId: " + toStr(video.videoId) + "\\n";',
        '    out += "duration: " + toStr(safe(video,["meta","duration"],"-")) + "\\n";',
        '    out += "title: " + toStr(safe(video,["meta","title"],"-"));',
        '  } else {',
        '    out += "videoId: (not matched)";',
        '  }',
        '} catch(e) { out = "data.json not linked"; }',
        'out;'
    ].join("\n");

    // info_position
    // Positions this text layer baseline at the vertical and horizontal center of the comp.
    // Intended as a safe default position for the info debug layer.
    globalObj.AE_EXPRESSIONS["info_position"] = [
        '// info_position — centered in comp',
        '[0 + thisComp.width * 0.05, 0 + thisComp.height * 0.05];'
    ].join("\n");

    // ── claim ────────────────────────────────────────────────────────────────
    // Source of truth: expression_ae/claim/ and expression_ae/opacity/
    // Bundled inline for installation compatibility.
    // To update: edit the source .js file, then copy its content into the array below.

    // claim_source_text — sourceText_json_wire_simple.js
    globalObj.AE_EXPRESSIONS["claim_source_text"] = [
        'var FOOTAGE_NAME = "data.json";',
        'function ctrl(name, def) {',
        '  try { return effect(name)(name.match(/Menu/i) ? "Menu" : "Slider").value; }',
        '  catch (e) { return def; }',
        '}',
        'var DATA_KEY_OPTIONS = ["claim", "disclaimer", "logo", "subtitles", "super_A", "super_B"];',
        'var ORIENT_OPTIONS = ["Auto", "Landscape", "Portrait"];',
        'var _dkIdx = Math.round(ctrl("Data Key Menu", 1)) - 1;',
        'var _omIdx = Math.round(ctrl("Orientation Menu", 1)) - 1;',
        'var DATA_KEY = DATA_KEY_OPTIONS[Math.max(0, Math.min(DATA_KEY_OPTIONS.length - 1, _dkIdx))];',
        'var desiredLine = Math.round(ctrl("Desired Line", 1));',
        'var ORIENT_MODE = ORIENT_OPTIONS[Math.max(0, Math.min(ORIENT_OPTIONS.length - 1, _omIdx))];',
        'var nameShift = Math.round(ctrl("Name Shift", 1));',
        'var compOrientation;',
        'var nameLower = thisComp.name.toLowerCase();',
        'if (ORIENT_MODE === "Landscape") { compOrientation = "landscape"; }',
        'else if (ORIENT_MODE === "Portrait") { compOrientation = "portrait"; }',
        'else {',
        '  var compAR = (thisComp.width / Math.max(1, thisComp.height));',
        '  compOrientation = compAR > 1 ? "landscape" : "portrait";',
        '  if (nameLower.indexOf("_landscape") >= 0) compOrientation = "landscape";',
        '  else if (nameLower.indexOf("_portrait") >= 0) compOrientation = "portrait";',
        '}',
        'var token1 = 0 + nameShift; var token2 = 1 + nameShift;',
        'function baseVideoId() {',
        '  var p = thisComp.name.split("_");',
        '  return (p.length >= 2) ? (p[token1] + "_" + p[token2]) : "";',
        '}',
        'var baseId = baseVideoId();',
        'var orientedId = baseId ? (baseId + "_" + compOrientation) : "";',
        'var directId = thisComp.name;',
        'function pickFromArray(arr, lineNum) {',
        '  if (!arr || arr.length === 0) return "";',
        '  var first = arr[0];',
        '  if (typeof first === "string") {',
        '    var idx = Math.max(0, Math.min(arr.length - 1, lineNum - 1));',
        '    return (arr[idx] || "") + "";',
        '  } else {',
        '    for (var i = 0; i < arr.length; i++) {',
        '      var it = arr[i];',
        '      if (it && it.line == lineNum) return (it.text || "") + "";',
        '    }',
        '    return "";',
        '  }',
        '}',
        'function findVideo(data, candidates) {',
        '  if (!data || !data.videos) return null;',
        '  var vids = data.videos;',
        '  for (var c = 0; c < candidates.length; c++) {',
        '    var target = (candidates[c] + "").toLowerCase();',
        '    if (!target) continue;',
        '    for (var i = 0; i < vids.length; i++) {',
        '      var v = vids[i];',
        '      if ((v.videoId + "").toLowerCase() === target) return v;',
        '    }',
        '  }',
        '  return null;',
        '}',
        'function getGlobalArray(data, key, compOrientation) {',
        '  if (!data) return null;',
        '  var block = data[key];',
        '  if (!block) return null;',
        '  if (block instanceof Array) return block;',
        '  return block[compOrientation] || null;',
        '}',
        'function getText(data, orientedId, baseId, directId, key, lineNum, compOrientation) {',
        '  if (!data) return "";',
        '  var vid = findVideo(data, [orientedId, directId, baseId]);',
        '  if (vid) {',
        '    var arr = vid[key];',
        '    var txt = pickFromArray(arr, lineNum);',
        '    if (txt) return txt;',
        '  }',
        '  var g = getGlobalArray(data, key, compOrientation);',
        '  return pickFromArray(g, lineNum);',
        '}',
        'try {',
        '  var data = footage(FOOTAGE_NAME).sourceData;',
        '  getText(data, orientedId, baseId, directId, DATA_KEY, desiredLine, compOrientation);',
        '} catch (e) { ""; }'
    ].join("\n");

    // claim_anchor — anchor_baseline_centered_text.js
    globalObj.AE_EXPRESSIONS["claim_anchor"] = [
        'var is3D = thisLayer.threeDLayer;',
        'try {',
        '  var r = sourceRectAtTime(time, false);',
        '  var w = Math.max(1, r.width);',
        '  var ax = r.left + w/2;',
        '  var ay = 6;',
        '  is3D ? [ax, ay, value[2]] : [ax, ay];',
        '} catch (e) {',
        '  value;',
        '}'
    ].join("\n");

    // claim_position — position_baseline_locked_text_multiline.js
    globalObj.AE_EXPRESSIONS["claim_position"] = [
        'var holder = thisComp.layer("locker_Claim");',
        'var group  = holder.content("PLACEHOLDER");',
        'var rect   = group.content("Rectangle Path 1");',
        'function norm(v){ var L = length(v,[0,0,0]); return (L>0)? v/L : v; }',
        'var gp   = group.transform.position;',
        'var C    = holder.toComp(gp);',
        'var Xax  = norm(holder.toCompVec([1,0,0]));',
        'var Yax  = norm(holder.toCompVec([0,1,0]));',
        'var cCtr = C;',
        'var cR   = holder.toComp([gp[0] + rect.size[0]/2, gp[1]]);',
        'var cT   = holder.toComp([gp[0], gp[1] - rect.size[1]/2]);',
        'var halfW = length(cR - cCtr);',
        'var halfH = length(cT - cCtr);',
        'function ctrl(name, def){',
        '  try{ return holder.effect(name)(name.match(/Menu/i) ? "Menu" : "Slider").value; } catch(e){ return def; }',
        '}',
        'var pad = Math.max(0, ctrl("Padding", 0));',
        'var ax  = Math.max(-1, Math.min(1, ctrl("Align X", 0)));',
        'var ay  = Math.max(-1, Math.min(1, ctrl("Align Y", 0)));',
        'halfW = Math.max(0, halfW - pad);',
        'halfH = Math.max(0, halfH - pad);',
        'var P = C + Xax*(ax*halfW) + Yax*(ay*halfH);',
        'function isText(li){ try{ li.text.sourceText; return true; } catch(e) { return false; } }',
        'if (isText(thisLayer)){',
        '  var r  = sourceRectAtTime(time, false);',
        '  var w  = Math.max(1, r.width);',
        '  var bx = r.left + w/2;',
        '  var txtStr = ""; try { txtStr = text.sourceText + ""; } catch(e) {}',
        '  var lineCount = 1;',
        '  if (txtStr.length) {',
        '    var norm2 = txtStr.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
        '    lineCount = norm2.split("\\n").length;',
        '  }',
        '  var multiline = lineCount > 1;',
        '  var deltaC;',
        '  if (multiline) {',
        '    var centerY = r.top + r.height/2;',
        '    var centerComp = toComp([bx, centerY]);',
        '    deltaC = P - centerComp;',
        '  } else {',
        '    var baselineComp = toComp([bx, 0]);',
        '    deltaC = P - baselineComp;',
        '  }',
        '  thisLayer.threeDLayer ? value + [deltaC[0], deltaC[1], 0] : value + deltaC;',
        '} else {',
        '  thisLayer.threeDLayer ? [P[0], P[1], value[2]] : P;',
        '}'
    ].join("\n");

    // claim_scale — scale_uniform_contain_v02.js
    globalObj.AE_EXPRESSIONS["claim_scale"] = [
        'var holder = thisComp.layer("locker_Claim");',
        'var group  = holder.content("PLACEHOLDER");',
        'var rect   = group.content("Rectangle Path 1");',
        'var gp = group.transform.position;',
        'var cC = holder.toComp(gp);',
        'var cR = holder.toComp([gp[0] + rect.size[0]/2, gp[1]]);',
        'var cL = holder.toComp([gp[0] - rect.size[0]/2, gp[1]]);',
        'var cT = holder.toComp([gp[0], gp[1] - rect.size[1]/2]);',
        'var cB = holder.toComp([gp[0], gp[1] + rect.size[1]/2]);',
        'var holderW = Math.max(1, length(cL, cR));',
        'var holderH = Math.max(1, length(cT, cB));',
        'function ctrl(name, def){',
        '  try { return holder.effect(name)(name.match(/Menu/i) ? "Menu" : "Slider").value; } catch(e) { return def; }',
        '}',
        'var pad = Math.max(0, ctrl("Padding", 0));',
        'holderW = Math.max(1, holderW - 2*pad);',
        'holderH = Math.max(1, holderH - 2*pad);',
        'function isText(li){ try{ li.text.sourceText; return true; } catch(e){ return false; } }',
        'var _txtDep = (function(){',
        '  try { return thisLayer.text.sourceText.text; } catch(e) { return ""; }',
        '})();',
        'function safeTextSize(){',
        '  function rectAt(t){ var r = sourceRectAtTime(t, false); return [r.width, r.height]; }',
        '  var w = 0, h = 0;',
        '  var r0 = rectAt(time); w = r0[0]; h = r0[1];',
        '  if ((w < 1 || h < 1) && time > thisComp.displayStartTime){',
        '    var tPrev = time - thisComp.frameDuration;',
        '    var r1 = rectAt(tPrev);',
        '    w = Math.max(w, r1[0]); h = Math.max(h, r1[1]);',
        '  }',
        '  return [Math.max(1, w), Math.max(1, h)];',
        '}',
        'function contentSize(li){',
        '  if (isText(li)){ return safeTextSize(); }',
        '  try {',
        '    var r = li.sourceRectAtTime(time, false);',
        '    if (r.width > 0 && r.height > 0) return [r.width, r.height];',
        '  } catch(e){}',
        '  return [Math.max(1, li.width), Math.max(1, li.height)];',
        '}',
        'var s = contentSize(thisLayer);',
        'var fit = Math.min(holderW / s[0], holderH / s[1]) * 100;',
        'var base = value[0];',
        'var k = Math.min(base, fit);',
        'thisLayer.threeDLayer ? [k, k, value[2]] : [k, k];'
    ].join("\n");

    // claim_opacity — opacity_fadein_onTime_v08.js
    globalObj.AE_EXPRESSIONS["claim_opacity"] = [
        'var FOOTAGE_NAME = "data.json";',
        'function ctrl(name, def) {',
        '  try { return effect(name)(name.match(/Menu/i) ? "Menu" : "Slider").value; }',
        '  catch (e) { return def; }',
        '}',
        'var DATA_KEY_OPTIONS = ["claim", "disclaimer", "logo", "subtitles", "super_A", "super_B"];',
        'var _dkIdx = Math.round(ctrl("Data Key Menu", 1)) - 1;',
        'var DATA_KEY = DATA_KEY_OPTIONS[Math.max(0, Math.min(DATA_KEY_OPTIONS.length - 1, _dkIdx))];',
        'var desiredLine = Math.round(ctrl("Desired Line", 0));',
        'var FADE_IN   = ctrl("Fade In",    0);',
        'var FADE_OUT  = ctrl("Fade Out",   0);',
        'var OPAC_IN   = ctrl("Opacity In", 0);',
        'var nameShift = Math.round(ctrl("Name Shift", 1));',
        'var compAR = thisComp.width / Math.max(1, thisComp.height);',
        'var compOrientation = compAR > 1 ? "landscape" : "portrait";',
        'var nameLower = thisComp.name.toLowerCase();',
        'if (nameLower.indexOf("_landscape") >= 0) compOrientation = "landscape";',
        'else if (nameLower.indexOf("_portrait") >= 0) compOrientation = "portrait";',
        'var token1 = 0 + nameShift; var token2 = 1 + nameShift;',
        'function baseVideoId(){ var p = thisComp.name.split("_"); return (p.length >= 2) ? (p[token1] + "_" + p[token2]) : ""; }',
        'var baseId = baseVideoId();',
        'var orientedId = baseId ? (baseId + "_" + compOrientation) : "";',
        'var directId = thisComp.name;',
        'function findVideo(data, candidates){',
        '  if (!data || !data.videos) return null;',
        '  var vids = data.videos;',
        '  for (var c=0;c<candidates.length;c++){',
        '    var target = (candidates[c] + "").toLowerCase();',
        '    if (!target) continue;',
        '    for (var i=0;i<vids.length;i++){',
        '      var v = vids[i];',
        '      if ((v.videoId + "").toLowerCase() === target) return v;',
        '    }',
        '  }',
        '  return null;',
        '}',
        'function getGlobalArray(data, key){',
        '  if (!data) return null;',
        '  var blk = data[key];',
        '  if (!blk) return null;',
        '  if (blk instanceof Array) return blk;',
        '  return blk[compOrientation] || null;',
        '}',
        'function collectSegments(videoObj, key){',
        '  var segs = [];',
        '  if (!videoObj) return segs;',
        '  var arr = videoObj[key];',
        '  if (!arr) return segs;',
        '  if (key === "subtitles" && desiredLine === 0){',
        '    for (var i=0;i<arr.length;i++){',
        '      var it = arr[i]; if (!it) continue;',
        '      var s = Number(it["in"]), e = Number(it["out"]);',
        '      if (!isNaN(s) && !isNaN(e) && e > s) segs.push([s,e]);',
        '    }',
        '    return segs;',
        '  }',
        '  var lineNum = desiredLine < 1 ? 1 : desiredLine;',
        '  for (var j=0;j<arr.length;j++){',
        '    var it2 = arr[j];',
        '    if (it2 && it2.line == lineNum){',
        '      var ss = Number(it2["in"]), ee = Number(it2["out"]);',
        '      if (!isNaN(ss) && !isNaN(ee) && ee > ss) segs.push([ss,ee]);',
        '      break;',
        '    }',
        '  }',
        '  return segs;',
        '}',
        'function mergeSegments(list){',
        '  if (list.length <= 1) return list;',
        '  list.sort(function(a,b){ return a[0]-b[0]; });',
        '  var out = [list[0]];',
        '  for (var i=1;i<list.length;i++){',
        '    var cur = list[i]; var prev = out[out.length-1];',
        '    if (cur[0] <= prev[1]){ if (cur[1] > prev[1]) prev[1] = cur[1]; } else { out.push(cur); }',
        '  }',
        '  return out;',
        '}',
        'function fadeOpacity(t, sT, eT, fin){',
        '  if (fin <= 0.000001 || fin <= thisComp.frameDuration) return 100;',
        '  var progress = Math.min(Math.max((t - sT) / fin, 0), 1);',
        '  return OPAC_IN + (100 - OPAC_IN) * progress;',
        '}',
        'function fadeOutOpacity(t, outStart, outEnd, fout){',
        '  if (fout <= 0.000001 || fout <= thisComp.frameDuration) return OPAC_IN;',
        '  var progress = Math.min(Math.max((t - outStart) / fout, 0), 1);',
        '  return 100 + (OPAC_IN - 100) * progress;',
        '}',
        'var dataRef = null, videoObj = null, segments = [], hasGlobalFallback = false;',
        'try {',
        '  dataRef = footage(FOOTAGE_NAME).sourceData;',
        '  videoObj = findVideo(dataRef, [orientedId, directId, baseId]);',
        '  segments = collectSegments(videoObj, DATA_KEY);',
        '  if (!segments.length){',
        '    var gArr = getGlobalArray(dataRef, DATA_KEY);',
        '    if (gArr && gArr.length) hasGlobalFallback = true;',
        '  }',
        '} catch(err){}',
        'if (segments.length === 0){',
        '  hasGlobalFallback ? 100 : 0;',
        '} else {',
        '  segments = mergeSegments(segments);',
        '  var t = time;',
        '  var active = null;',
        '  for (var iS=0;iS<segments.length;iS++){',
        '    var sg = segments[iS];',
        '    if (t >= sg[0] && t < sg[1]) { active = sg; break; }',
        '  }',
        '  if (!active){ 0; }',
        '  else {',
        '    var sT = active[0], eT = active[1];',
        '    var segLen = Math.max(0.0005, eT - sT);',
        '    var fin = Math.min(Math.max(0.0005, FADE_IN), segLen);',
        '    var fout = Math.min(Math.max(0.0005, FADE_OUT), segLen);',
        '    var outStart = eT - fout;',
        '    (t < sT) ? 0 :',
        '    (t < sT + fin) ? fadeOpacity(t, sT, eT, fin) :',
        '    (t >= outStart && t < eT) ? fadeOutOpacity(t, outStart, eT, fout) : 100;',
        '  }',
        '}'
    ].join("\n");

}($.global));