// Expressions Library — expressions_library.jsx
// Registry of named AE expression strings used by layer_template.jsx.
// Keys are symbolic names referenced from layer_templates_library.jsx item definitions.
// Expression strings are raw AE expression source — do not include JSON escaping.
//
// Usage: always loaded by layer_template.jsx via $.evalFile before item execution.
// Direct execution produces no side effects.

#target aftereffects

(function initExpressionsLibrary(globalObj) {
    if (!globalObj) return;
    if (!globalObj.AE_EXPRESSIONS || typeof globalObj.AE_EXPRESSIONS !== "object") {
        globalObj.AE_EXPRESSIONS = {};
    }

    // ── info ─────────────────────────────────────────────────────────────────

    // info_position
    // Positions this text layer baseline at the vertical and horizontal center of the comp.
    // Intended as a safe default position for the info debug layer.
    globalObj.AE_EXPRESSIONS["info_position"] = [
        '// info_position — centered in comp',
        '[0 + thisComp.width * 0.05, 0 + thisComp.height * 0.05];'
    ].join("\n");

// >>> AE_EXPRESSIONS_BUNDLE:START
    // AUTO-GENERATED: AE expressions bundle
    // Do not edit this block manually.
    // Source of truth lives in expression_ae/*.js files.

    // ── info (generated) ─────────────────────────────────────────────────────

    // info_source_text — expression_ae/sourceText/sourceText_json_info.js
    globalObj.AE_EXPRESSIONS["info_source_text"] = [
        '// sourceText_json_info v04 251209 (per-video metadata inspector)',
        '// Builds an informational multiline string combining global metadata and the resolved video object\'s metadata.',
        '// Intended for a debug / QA text layer inside AE.',
        '// Output example:',
        '// client: <client>\\ncampaign: <campaign>\\nvideoId: <resolvedVideoId>\\ncompOrient(meta): <video.meta.orientation>\\ncompOrient(test): <computedFromAR>\\nduration(meta): <video.meta.duration>\\ntitle: <video.meta.title>\\nsubtitles: <count>',
        '// If a field is missing it shows \'-\'. If video not found, returns basic global info only.',
        '',
        'var FOOTAGE_NAME = "data.json"; // name of JSON footage',
        'var nameShift = 1;  // 0 = Title_30s; 1 = Clien_Title_30s; 2 = Client_Brand_Title_30s',
        '',
        '// ---------- Orientation detection (computed test) ----------',
        'var ar = thisComp.width / Math.max(1, thisComp.height);',
        'function orientFromAR(r){ return r > 1 ? "landscape" : "portrait"; } // square => portrait',
        'var compOrientTest = orientFromAR(ar);',
        '',
        '// Allow explicit override via suffix (_landscape / _portrait)',
        'var nameLower = thisComp.name.toLowerCase();',
        'if (nameLower.indexOf("_landscape") >= 0) compOrientTest = "landscape";',
        'else if (nameLower.indexOf("_portrait") >= 0) compOrientTest = "portrait";',
        '',
        '// ---------- Derive candidate videoIds ----------',
        'var token1 = 0 + nameShift;',
        'var token2 = 1 + nameShift;',
        '',
        'function baseVideoId() {',
        '  var p = thisComp.name.split("_");',
        '  return (p.length >= 2) ? (p[token1] + "_" + p[token2]) : ""; // e.g. Title_30s',
        '}',
        'var baseId = baseVideoId();',
        'var orientedId = baseId ? (baseId + "_" + compOrientTest) : ""; // oriented video id suffix pattern',
        'var directId = thisComp.name; // full comp name fallback',
        '',
        'function findVideo(data, candidates) {',
        '  if (!data || !data.videos) return null;',
        '  var vids = data.videos;',
        '  for (var c = 0; c < candidates.length; c++) {',
        '    var target = (candidates[c] + "").toLowerCase();',
        '    if (!target) continue;',
        '    for (var i = 0; i < vids.length; i++) {',
        '      var v = vids[i];',
        '      if ((v.videoId + "").toLowerCase() === target) return v;',
        '    }',
        '  }',
        '  return null;',
        '}',
        '',
        '// ---------- Safe access helpers ----------',
        'function safe(obj, path, defVal) {',
        '  try {',
        '    var ref = obj;',
        '    for (var i = 0; i < path.length; i++) {',
        '      if (!ref) return defVal;',
        '      ref = ref[path[i]];',
        '    }',
        '    return (ref == null) ? defVal : ref;',
        '  } catch (e) { return defVal; }',
        '}',
        '',
        'function toStr(v){ return (v == null) ? "-" : (v + ""); }',
        '',
        '',
        '//========================AspectAuto_v02_230451',
        'let sizeX = thisComp.width;',
        'let sizeY = thisComp.height;',
        'function greatestCommonDivisor (x, y) {',
        '	return (y == 0) ? x : greatestCommonDivisor (y, x%y);',
        '        }',
        'function aspect(x, y) {',
        '	let r = greatestCommonDivisor(sizeX, sizeY);',
        '	return (x/r) + ":" + y/r;',
        '}',
        'resultAspect = aspect(sizeX, sizeY);',
        '',
        'var out = "";',
        'try {',
        '  var data = footage(FOOTAGE_NAME).sourceData;',
        '  var globalMeta = data ? data.metadataGlobal : null;',
        '  var video = findVideo(data, [orientedId, directId, baseId]);',
        '',
        '  var client   = toStr(safe(globalMeta, ["client"], "-"));',
        '  var campaign = toStr(safe(globalMeta, ["campaign"], "-"));',
        '  var country = toStr(safe(globalMeta, ["country"], "-"));',
        '  var language = toStr(safe(globalMeta, ["language"], "-"));',
        '  var videoId  = video ? toStr(video.videoId) : "(video not found)";',
        '  var vMeta    = video ? video.metadata : null;',
        '  var vOrient  = toStr(safe(vMeta, ["orientation"], "-"));',
        '  var vDur     = toStr(safe(vMeta, ["duration"], "-"));',
        '  var vTitle   = toStr(safe(vMeta, ["title"], "-"));',
        '  var subsFlag = toStr(safe(vMeta, ["subtitle_flag"], "-"));',
        '  var disclaimerFlag = toStr(safe(vMeta, ["disclaimer_flag"], "-"));',
        '  var disclaimerFlag_02 = toStr(safe(vMeta, ["disclaimer_02_flag"], "-"));',
        '  var super_A_flag = toStr(safe(vMeta, ["super_A_flag"], "-"));',
        '  var super_B_flag = toStr(safe(vMeta, ["super_B_flag"], "-"));',
        '  var logo_animFlag = toStr(safe(vMeta, ["logo_anim_flag"], "-"));',
        '  var logo_02_flag = toStr(safe(vMeta, ["logo_02_flag"], "-"));',
        '  var logo_03_flag = toStr(safe(vMeta, ["logo_03_flag"], "-"));',
        '  var logo_04_flag = toStr(safe(vMeta, ["logo_04_flag"], "-"));',
        '  var logo_05_flag = toStr(safe(vMeta, ["logo_05_flag"], "-"));',
        '  var claim_01_flag = toStr(safe(vMeta, ["claim_01_flag"], "-"));',
        '  var claim_02_flag = toStr(safe(vMeta, ["claim_02_flag"], "-"));',
        '  var subsLen  = video && video.subtitles instanceof Array ? (video.subtitles.length+"") : (video ? "0" : "-");',
        '        ',
        '  out  = "client: " + client;',
        '  out += "\\rcampaign: " + campaign;',
        '  out += "\\rcountry: " + country;',
        '  out += "\\rlanguage: " + language;',
        '  out += "\\rvideoId: " + videoId;',
        '  out += "\\rdata(compOrientMeta): " + vOrient;',
        '  out += "\\rcompOrient(test): " + compOrientTest;',
        '  out += "\\raspect ratio: " + resultAspect;',
        '  out += "\\rduration(meta): " + vDur;',
        '  out += "\\rtitle: " + vTitle;',
        '  out += "\\rsubtitles: " + subsFlag;',
        '  out += "\\rdisclaimer: " + disclaimerFlag;',
        '  out += "\\rsuper_A: " + super_A_flag;',
        '  out += "\\rsuper_B: " + super_B_flag;',
        '  out += "\\rlogo_anim: " + logo_animFlag;',
        '  out += "\\rlogo_02: " + logo_02_flag;',
        '  out += "\\rlogo_03: " + logo_03_flag;',
        '  out += "\\rlogo_04: " + logo_04_flag;',
        '  out += "\\rlogo_05: " + logo_05_flag;',
        '  out += "\\rclaim_01: " + claim_01_flag;',
        '  out += "\\rclaim_02: " + claim_02_flag;',
        '  out += "\\rsubtitles: " + subsLen;',
        '} catch (err) {',
        '  out = "(metadata unavailable)";',
        '}',
        '',
        'out;'
    ].join("\n");

    // ── claim (generated) ────────────────────────────────────────────────────

    // claim_source_text — expression_ae/claim/sourceText_json_wire_simple.js
    globalObj.AE_EXPRESSIONS["claim_source_text"] = [
        '// sourceText_json_wire_simple 260502',
        '// not-time-gated, orientation-aware/override',
        '// ------------------------------------------------------------------------------',
        '// based on v05',
        '// Rewired for new JSON shape with orientation-specific top-level keys:',
        '//   claim: { landscape:[...], portrait:[...] }',
        '// Video objects duplicated per orientation with videoId suffixed: e.g. WTAVL_120s_landscape',
        '// ------------------------------------------------------------------------------',
        '// Usage:',
        '//   Set DATA_KEY to one of: "claim", "disclaimer", "logo", "subtitles" (if you adapt logic)',
        '//   desiredLine is 1-based for line selection within video-level arrays or top-level arrays.',
        '//   Orientation auto-detected from comp aspect ratio (>=1 => landscape, else portrait).',
        '',
        'var FOOTAGE_NAME = "data.json";  // JSON footage name in Project panel',
        '',
        '// Read controls from this text layer (Effects > Expression Controls)',
        '// Required effects:',
        '//   Dropdown Menu Control  "Data Key Menu"     -> claim | disclaimer | logo | subtitles | super_A',
        '//   Slider Control         "Desired Line"      -> 0 = time-driven multi; >0 fixed line',
        '//   Dropdown Menu Control  "Orientation Menu"  -> Auto | Landscape | Portrait',
        '//   Slider Control         "Name Shift"        -> 0,1,2...',
        'function ctrl(name, def) {',
        '  try {',
        '    return effect(name)(name.match(/Menu/i) ? "Menu" : "Slider").value;',
        '  } catch (e) { return def; }',
        '}',
        '',
        '// Keep menu arrays in the same order as Dropdown items in AE.',
        'var DATA_KEY_OPTIONS = ["claim", "disclaimer", "logo", "subtitles", "super_A", "super_B"];',
        'var ORIENT_OPTIONS = ["Auto", "Landscape", "Portrait"];',
        '',
        'var _dkIdx = Math.round(ctrl("Data Key Menu", 1)) - 1;      // default "disclaimer"',
        'var _omIdx = Math.round(ctrl("Orientation Menu", 1)) - 1;   // default "Auto"',
        '',
        'var DATA_KEY = DATA_KEY_OPTIONS[Math.max(0, Math.min(DATA_KEY_OPTIONS.length - 1, _dkIdx))];',
        'var desiredLine = Math.round(ctrl("Desired Line", 1));      // 0=time-driven multi; >0 fixed line',
        'var ORIENT_MODE = ORIENT_OPTIONS[Math.max(0, Math.min(ORIENT_OPTIONS.length - 1, _omIdx))];',
        'var nameShift = Math.round(ctrl("Name Shift", 1));  // 0 = Title_30s; 1 = Clien_Title_30s; 2 = Client_Brand_Title_30s',
        '',
        '// -------- Orientation detection / override -------- ',
        '// Determine compOrientation from comp aspect ratio OR from comp name suffix if present',
        'var compOrientation;',
        'var nameLower = thisComp.name.toLowerCase();',
        'if (ORIENT_MODE === "Landscape") {',
        '  compOrientation = "landscape";',
        '} else if (ORIENT_MODE === "Portrait") {',
        '  compOrientation = "portrait";',
        '} else {',
        '  // Auto: aspect-based with suffix override',
        '  var compAR = (thisComp.width / Math.max(1, thisComp.height));',
        '  compOrientation = compAR > 1 ? "landscape" : "portrait"; // square -> portrait',
        '  // Explicit override if comp name contains _landscape or _portrait',
        '  if (nameLower.indexOf("_landscape") >= 0) compOrientation = "landscape";',
        '  else if (nameLower.indexOf("_portrait") >= 0) compOrientation = "portrait";',
        '}',
        '',
        '// -------- VideoId derivation --------',
        '// Derive base video id from comp name: "Title_15s_*" → "Title_15s"; oriented id adds suffix',
        'var token1 = 0 + nameShift;',
        'var token2 = 1 + nameShift;',
        '',
        'function baseVideoId() {',
        '  var p = thisComp.name.split("_");',
        '  return (p.length >= 2) ? (p[token1] + "_" + p[token2]) : ""; // Title_15s',
        '}',
        'var baseId = baseVideoId();',
        'var orientedId = baseId ? (baseId + "_" + compOrientation) : ""; // Title_15s_landscape',
        '',
        '// If comp name already equals a videoId exactly, use it directly',
        'var directId = thisComp.name; // fallback candidate',
        '',
        'function pickFromArray(arr, lineNum) {',
        '  if (!arr || arr.length === 0) return "";',
        '  var first = arr[0];',
        '  if (typeof first === "string") {',
        '    var idx = Math.max(0, Math.min(arr.length - 1, lineNum - 1));',
        '    return (arr[idx] || "") + "";',
        '  } else {',
        '    for (var i = 0; i < arr.length; i++) {',
        '      var it = arr[i];',
        '      if (it && it.line == lineNum) return (it.text || "") + "";',
        '    }',
        '    return "";',
        '  }',
        '}',
        '',
        'function findVideo(data, candidates) {',
        '  if (!data || !data.videos) return null;',
        '  var vids = data.videos;',
        '  for (var c = 0; c < candidates.length; c++) {',
        '    var target = (candidates[c] + "").toLowerCase();',
        '    if (!target) continue;',
        '    for (var i = 0; i < vids.length; i++) {',
        '      var v = vids[i];',
        '      if ((v.videoId + "").toLowerCase() === target) return v;',
        '    }',
        '  }',
        '  return null;',
        '}',
        '',
        'function getGlobalArray(data, key, compOrientation) {',
        '  if (!data) return null;',
        '  var block = data[key];',
        '  if (!block) return null;',
        '  // New shape: object of orientations',
        '  if (block instanceof Array) {',
        '    // Legacy shape fallback',
        '    return block;',
        '  } else {',
        '    return block[compOrientation] || null;',
        '  }',
        '}',
        '',
        'function getText(data, orientedId, baseId, directId, key, lineNum, compOrientation) {',
        '  if (!data) return "";',
        '  // Try oriented video id first, then direct comp name, then base id (legacy)',
        '  var vid = findVideo(data, [orientedId, directId, baseId]);',
        '  if (vid) {',
        '    var arr = vid[key];',
        '    var txt = pickFromArray(arr, lineNum);',
        '    if (txt) return txt;',
        '  }',
        '  // Fallback to top-level orientation-specific array',
        '  var g = getGlobalArray(data, key, compOrientation);',
        '  return pickFromArray(g, lineNum);',
        '}',
        '',
        'try {',
        '  var data = footage(FOOTAGE_NAME).sourceData;',
        '  getText(data, orientedId, baseId, directId, DATA_KEY, desiredLine, compOrientation);',
        '} catch (e) {',
        '  "";',
        '}'
    ].join("\n");

    // claim_anchor — expression_ae/claim/anchor_baseline_centered_text.js
    globalObj.AE_EXPRESSIONS["claim_anchor"] = [
        '// anchor_baseline_centered_text',
        '// TEXT layer ► Anchor Point — Baseline-centered (no Y drift)',
        'var is3D = thisLayer.threeDLayer;',
        '',
        'try {',
        '  var r = sourceRectAtTime(time, false);',
        '  var w = Math.max(1, r.width); // avoid zero-width when text is empty',
        '  var ax = r.left + w/2;        // horizontal center of visible text',
        '  var ay = 6;                   // baseline is Y = 0 for POINT text',
        '  is3D ? [ax, ay, value[2]] : [ax, ay];',
        '} catch (e) {',
        '  // Fallback: keep existing anchor if SRAT isn\'t available',
        '  value;',
        '}'
    ].join("\n");

    // claim_position — expression_ae/claim/position_baseline_locked_text_multiline.js
    globalObj.AE_EXPRESSIONS["claim_position"] = [
        '// position_baseline_locked_text_multiline',
        '// TARGET ► Position — vertical centering for multiline TEXT',
        'var holder = thisComp.layer("locker_Claim");',
        'var group  = holder.content("PLACEHOLDER");',
        'var rect   = group.content("Rectangle Path 1");',
        '',
        '// --- Holder center/axes/half-extents in comp space (rotation aware) ---',
        'function norm(v){ var L = length(v,[0,0,0]); return (L>0)? v/L : v; }',
        'var gp   = group.transform.position;',
        'var C    = holder.toComp(gp);',
        'var Xax  = norm(holder.toCompVec([1,0,0]));',
        'var Yax  = norm(holder.toCompVec([0,1,0]));',
        'var cCtr = C;',
        'var cR   = holder.toComp([gp[0] + rect.size[0]/2, gp[1]]);',
        'var cT   = holder.toComp([gp[0], gp[1] - rect.size[1]/2]);',
        'var halfW = length(cR - cCtr);',
        'var halfH = length(cT - cCtr);',
        '',
        '// Optional controls',
        'function ctrl(name, def){',
        '  try{ return holder.effect(name)(name.match(/Menu/i) ? "Menu" : "Slider").value; } catch(e){ return def; }',
        '}',
        'var pad = Math.max(0, ctrl("Padding", 0));',
        'var ax  = Math.max(-1, Math.min(1, ctrl("Align X", 0))); // -1..1',
        'var ay  = Math.max(-1, Math.min(1, ctrl("Align Y", 0))); // -1..1',
        '// Automatic vertical centering for multiline TEXT (2D point text only).',
        '// Simplified: 1 line = baseline align; >=2 lines = compute baseline offset so block visually centers in holder.',
        '',
        'halfW = Math.max(0, halfW - pad);',
        'halfH = Math.max(0, halfH - pad);',
        '',
        '// Target comp-space point inside the placeholder',
        'var P = C + Xax*(ax*halfW) + Yax*(ay*halfH);',
        '',
        '// --- Baseline lock for TEXT layers ---',
        'function isText(li){ try{ li.text.sourceText; return true; } catch(e) { return false; } }',
        '',
        'if (isText(thisLayer)){',
        '  // Determine reference point in layer space we want to align to P.',
        '  // For baseline mode: [centerX, 0]. For vertical-centering: middle of text block.',
        '  var r  = sourceRectAtTime(time, false);',
        '  var w  = Math.max(1, r.width);',
        '  var bx = r.left + w/2;',
        '',
        '  // Count lines (split on CR or LF). If text empty treat as 1.',
        '  var txtStr = ""; try { txtStr = text.sourceText + ""; } catch(e) {}',
        '  var lineCount = 1;',
        '  if (txtStr.length) {',
        '    // Normalize newlines then split',
        '    var norm2 = txtStr.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
        '    lineCount = norm2.split("\\n").length;',
        '  }',
        '',
        '  var multiline = lineCount > 1;',
        '  var deltaC;',
        '  if (multiline) {',
        '    // Robust geometric center method:',
        '    // centerY = r.top + r.height/2 (layer space). Convert that point & baseline to comp, then shift so center hits P.',
        '    var centerY = r.top + r.height/2;',
        '    var centerComp = toComp([bx, centerY]);',
        '    deltaC = P - centerComp; // move layer so its current center lands at P',
        '  } else {',
        '    // Single line: align baseline centerX to P (baseline y=0)',
        '    var baselineComp = toComp([bx, 0]);',
        '    deltaC = P - baselineComp;',
        '  }',
        '',
        '  thisLayer.threeDLayer ? value + [deltaC[0], deltaC[1], 0] : value + deltaC;',
        '} else {',
        '  // Non-text: keep prior behavior (position to alignment target)',
        '  thisLayer.threeDLayer ? [P[0], P[1], value[2]] : P;',
        '}'
    ].join("\n");

    // claim_scale — expression_ae/claim/scale_uniform_contain_v02.js
    globalObj.AE_EXPRESSIONS["claim_scale"] = [
        '// scale_uniform_contain_v02',
        '// TARGET (Text) ► Scale — Contain, only shrink; JSON/text-safe',
        '',
        '// --- Holder rect (rotation/scale aware) ---',
        'var holder = thisComp.layer("locker_Claim");',
        'var group  = holder.content("PLACEHOLDER");',
        'var rect   = group.content("Rectangle Path 1");',
        '',
        'var gp = group.transform.position;',
        'var cC = holder.toComp(gp);',
        'var cR = holder.toComp([gp[0] + rect.size[0]/2, gp[1]]);',
        'var cL = holder.toComp([gp[0] - rect.size[0]/2, gp[1]]);',
        'var cT = holder.toComp([gp[0], gp[1] - rect.size[1]/2]);',
        'var cB = holder.toComp([gp[0], gp[1] + rect.size[1]/2]);',
        '',
        'var holderW = Math.max(1, length(cL, cR));',
        'var holderH = Math.max(1, length(cT, cB));',
        '',
        '// Optional padding from holder effects',
        'function ctrl(name, def){',
        '  try { return holder.effect(name)(name.match(/Menu/i) ? "Menu" : "Slider").value; } catch(e) { return def; }',
        '}',
        'var pad = Math.max(0, ctrl("Padding", 0));',
        'holderW = Math.max(1, holderW - 2*pad);',
        'holderH = Math.max(1, holderH - 2*pad);',
        '',
        '// --- Dependencies & robust text measurement ---',
        'function isText(li){ try{ li.text.sourceText; return true; } catch(e){ return false; } }',
        '',
        '// Force AE to evaluate after Source Text expression by referencing it (dependency only).',
        '// We don\'t actually use the string here; it\'s just to ensure correct evaluation order.',
        'var _txtDep = (function(){',
        '  try { return thisLayer.text.sourceText.text; } catch(e) { return ""; }',
        '})();',
        '',
        '// Safe sourceRectAtTime for text: tries current frame; if 0×0, tries previous frame.',
        'function safeTextSize(){',
        '  function rectAt(t){ var r = sourceRectAtTime(t, false); return [r.width, r.height]; }',
        '  var w = 0, h = 0;',
        '',
        '  // Try now',
        '  var r0 = rectAt(time);',
        '  w = r0[0]; h = r0[1];',
        '',
        '  // If empty (common right after JSON updates), try previous frame (if possible)',
        '  if ((w < 1 || h < 1) && time > thisComp.displayStartTime){',
        '    var tPrev = time - thisComp.frameDuration;',
        '    var r1 = rectAt(tPrev);',
        '    w = Math.max(w, r1[0]);',
        '    h = Math.max(h, r1[1]);',
        '  }',
        '',
        '  // Final clamp to avoid div-by-zero and accidental upscales',
        '  return [Math.max(1, w), Math.max(1, h)];',
        '}',
        '',
        'function contentSize(li){',
        '  if (isText(li)){',
        '    return safeTextSize(); // never fallback to comp size for text',
        '  }',
        '  // Non-text: SRAT if available, else layer dims',
        '  try {',
        '    var r = li.sourceRectAtTime(time, false);',
        '    if (r.width > 0 && r.height > 0) return [r.width, r.height];',
        '  } catch(e){}',
        '  return [Math.max(1, li.width), Math.max(1, li.height)];',
        '}',
        '',
        'var s = contentSize(thisLayer);',
        '',
        '// --- Only-shrink uniform contain ---',
        'var fit = Math.min(holderW / s[0], holderH / s[1]) * 100;',
        '',
        '// Baseline: respect your keyed X scale (never upscale beyond it)',
        'var base = value[0];',
        'var k = Math.min(base, fit);',
        '',
        'thisLayer.threeDLayer ? [k, k, value[2]] : [k, k];'
    ].join("\n");

    // claim_opacity — expression_ae/opacity/opacity_fadein_onTime_v08.js
    globalObj.AE_EXPRESSIONS["claim_opacity"] = [
        '// opacity_fadein_onTime_v08 260502',
        '// (orientation-aware, SINGLE KEY, fade in, fade out)',
        '',
        '// union does not work (of multiple segments when desiredLine == 0 for subtitles.)',
        '',
        '// Simplified from multi-key version: drive opacity from one user-defined data key.',
        '// JSON duplication per orientation (videoId suffixed, e.g. Title_30s_landscape).',
        '// Supported keys: (E.g. claim | disclaimer | logo | subtitles) timed arrays of objects with in/out; global arrays w/out timing;',
        '// CONFIG:',
        '//   DATA_KEY    → which array to read',
        '//   desiredLine → line number (1-based). For subtitles: if 0 gather ALL subtitle lines\' time windows (union)',
        '// Behavior:',
        '//   - Collect timed segments for the oriented video under DATA_KEY.',
        '//   - Opacity per segment: fade from OPAC_IN to 100 over FADE_IN starting at \'in\',',
        '//     then fade from 100 to OPAC_IN over FADE_OUT ending at \'out\'. Exclusive out: [in, out).',
        '//   - Multiple segments (e.g. subtitles lines) are treated as a union (any active segment → visible).',
        '//   - If no timed segments but a global orientation fallback array exists for DATA_KEY → constant 100.',
        '//   - Else → 0.',
        '// Notes:',
        '//   - Fade durations auto-clamped so they never exceed segment length.',
        '//   - Orientation: square treated as portrait; can override by suffix _landscape / _portrait in comp name.',
        '',
        '// -------- CONFIG --------',
        '// FOOTAGE_NAME stays inline; all other config comes from Expression Controls on this layer.',
        '//',
        '// Required effects (Effects > Expression Controls):',
        '//   Dropdown Menu Control  "Data Key Menu"  — items: claim | disclaimer | logo | subtitles | super_A',
        '//                                             Add further items in any order; keep this array in sync:',
        '//   Slider Control         "Desired Line"   — 0 = all / subtitle union; ≥1 = specific line (integer)',
        '//   Slider Control         "Fade In"        — seconds, decimals supported (e.g. 0.5)',
        '//   Slider Control         "Fade Out"       — seconds, decimals supported (e.g. 0.5)',
        '//   Slider Control         "Opacity In"     — 0–100',
        '//   Slider Control         "Name Shift"     — 0 = Title_30s | 1 = Client_Title_30s | 2 = Client_Brand_Title_30s',
        '',
        'var FOOTAGE_NAME = "data.json";',
        '',
        '// Read a named effect from this layer; Menu effects need the "Menu" property, Sliders need "Slider".',
        'function ctrl(name, def) {',
        '  try {',
        '    return effect(name)(name.match(/Menu/i) ? "Menu" : "Slider").value;',
        '  } catch (e) { return def; }',
        '}',
        '',
        '// Map Dropdown index (1-based) to a JSON key string.',
        '// Keep this array in the same order as the "Data Key Menu" dropdown items.',
        'var DATA_KEY_OPTIONS = ["claim", "disclaimer", "logo", "subtitles", "super_A", "super_B"];',
        'var _dkIdx = Math.round(ctrl("Data Key Menu", 1)) - 1; // 0-based',
        'var DATA_KEY = DATA_KEY_OPTIONS[Math.max(0, Math.min(DATA_KEY_OPTIONS.length - 1, _dkIdx))];',
        '',
        'var desiredLine = Math.round(ctrl("Desired Line", 0));',
        'var FADE_IN     = ctrl("Fade In",     0);   // float seconds',
        'var FADE_OUT    = ctrl("Fade Out",    0);   // float seconds',
        'var OPAC_IN     = ctrl("Opacity In",  0);   // 0–100',
        'var nameShift   = Math.round(ctrl("Name Shift", 1));',
        '',
        '// -------- Orientation detection --------',
        'var compAR = thisComp.width / Math.max(1, thisComp.height);',
        'var compOrientation = compAR > 1 ? "landscape" : "portrait";',
        'var nameLower = thisComp.name.toLowerCase();',
        'if (nameLower.indexOf("_landscape") >= 0) compOrientation = "landscape";',
        'else if (nameLower.indexOf("_portrait")  >= 0) compOrientation = "portrait";',
        '',
        '// -------- VideoId derivation --------',
        'var token1 = 0 + nameShift;',
        'var token2 = 1 + nameShift;',
        '',
        'function baseVideoId(){',
        '  var p = thisComp.name.split("_");',
        '  return (p.length >= 2) ? (p[token1] + "_" + p[token2]) : ""; // e.g. Title_30s',
        '}',
        'var baseId     = baseVideoId();',
        'var orientedId = baseId ? (baseId + "_" + compOrientation) : "";',
        'var directId   = thisComp.name;',
        '',
        'function findVideo(data, candidates){',
        '  if (!data || !data.videos) return null;',
        '  var vids = data.videos;',
        '  for (var c=0;c<candidates.length;c++){',
        '    var target = (candidates[c] + "").toLowerCase();',
        '    if (!target) continue;',
        '    for (var i=0;i<vids.length;i++){',
        '      var v = vids[i];',
        '      if ((v.videoId + "").toLowerCase() === target) return v;',
        '    }',
        '  }',
        '  return null;',
        '}',
        '',
        'function getGlobalArray(data, key){',
        '  if (!data) return null;',
        '  var blk = data[key];',
        '  if (!blk) return null;',
        '  if (blk instanceof Array) return blk;',
        '  return blk[compOrientation] || null;',
        '}',
        '',
        'function collectSegments(videoObj, key){',
        '  var segs = [];',
        '  if (!videoObj) return segs;',
        '  var arr = videoObj[key];',
        '  if (!arr) return segs;',
        '  if (key === "subtitles" && desiredLine === 0){',
        '    for (var i=0;i<arr.length;i++){',
        '      var it = arr[i]; if (!it) continue;',
        '      var s = Number(it["in"]), e = Number(it["out"]);',
        '      if (!isNaN(s) && !isNaN(e) && e > s) segs.push([s,e]);',
        '    }',
        '    return segs;',
        '  }',
        '  var lineNum = desiredLine < 1 ? 1 : desiredLine;',
        '  for (var j=0;j<arr.length;j++){',
        '    var it2 = arr[j];',
        '    if (it2 && it2.line == lineNum){',
        '      var ss = Number(it2["in"]), ee = Number(it2["out"]);',
        '      if (!isNaN(ss) && !isNaN(ee) && ee > ss) segs.push([ss,ee]);',
        '      break;',
        '    }',
        '  }',
        '  return segs;',
        '}',
        '',
        '// Optional: merge overlapping/touching segments for cleaner evaluation',
        'function mergeSegments(list){',
        '  if (list.length <= 1) return list;',
        '  list.sort(function(a,b){ return a[0]-b[0]; });',
        '  var out = [list[0]];',
        '  for (var i=1;i<list.length;i++){',
        '    var cur = list[i];',
        '    var prev = out[out.length-1];',
        '    if (cur[0] <= prev[1]){',
        '      if (cur[1] > prev[1]) prev[1] = cur[1];',
        '    } else {',
        '      out.push(cur);',
        '    }',
        '  }',
        '  return out;',
        '}',
        '',
        '// Fade from OPAC_IN to 100 over segment start window',
        'function fadeOpacity(t, sT, eT, fin){',
        '  if (fin <= 0.000001 || fin <= thisComp.frameDuration){',
        '    // Treat as instant',
        '    return 100;',
        '  }',
        '  var progress = (t - sT) / fin;',
        '  progress = Math.min(Math.max(progress, 0), 1);',
        '  return OPAC_IN + (100 - OPAC_IN) * progress;',
        '}',
        '',
        '// Fade from 100 to OPAC_IN over segment end window',
        'function fadeOutOpacity(t, outStart, outEnd, fout){',
        '  if (fout <= 0.000001 || fout <= thisComp.frameDuration){',
        '    // Treat as instant at out window start',
        '    return OPAC_IN;',
        '  }',
        '  var progress = (t - outStart) / fout;',
        '  progress = Math.min(Math.max(progress, 0), 1);',
        '  return 100 + (OPAC_IN - 100) * progress;',
        '}',
        '',
        'var dataRef = null, videoObj = null, segments = [], hasGlobalFallback = false;',
        'try {',
        '  dataRef = footage(FOOTAGE_NAME).sourceData;',
        '  videoObj = findVideo(dataRef, [orientedId, directId, baseId]);',
        '  segments = collectSegments(videoObj, DATA_KEY);',
        '  if (!segments.length){',
        '    var gArr = getGlobalArray(dataRef, DATA_KEY);',
        '    if (gArr && gArr.length) hasGlobalFallback = true;',
        '  }',
        '} catch(err){}',
        '',
        'if (segments.length === 0){',
        '  hasGlobalFallback ? 100 : 0;',
        '} else {',
        '  segments = mergeSegments(segments);',
        '  var t = time;',
        '  var active = null;',
        '  for (var iS=0;iS<segments.length;iS++){',
        '    var sg = segments[iS];',
        '    if (t >= sg[0] && t < sg[1]) { active = sg; break; }',
        '  }',
        '  if (!active){',
        '    0;',
        '  } else {',
        '    var sT = active[0], eT = active[1];',
        '    var segLen = Math.max(0.0005, eT - sT);',
        '    var fin = Math.min(Math.max(0.0005, FADE_IN), segLen);',
        '    var fout = Math.min(Math.max(0.0005, FADE_OUT), segLen);',
        '    var outStart = eT - fout;',
        '    (t < sT) ? 0 :',
        '    (t < sT + fin) ? fadeOpacity(t, sT, eT, fin) :',
        '    (t >= outStart && t < eT) ? fadeOutOpacity(t, outStart, eT, fout) : 100;',
        '  }',
        '}'
    ].join("\n");
// <<< AE_EXPRESSIONS_BUNDLE:END

}($.global));